/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui"],
        serif: ["serif"],
        mono: ["ui-monospace", "monospace"],
      },
      colors: {
        court: "rgb(var(--court) / <alpha-value>)",
        charcoal: "rgb(var(--charcoal) / <alpha-value>)",
        asphalt: "rgb(var(--asphalt) / <alpha-value>)",
        "asphalt-light": "rgb(var(--asphalt-light) / <alpha-value>)",
        "asphalt-muted": "rgb(var(--asphalt-muted) / <alpha-value>)",
        racket: "rgb(var(--racket) / <alpha-value>)",
        "racket-hover": "rgb(var(--racket-hover) / <alpha-value>)",
        turf: "rgb(var(--turf) / <alpha-value>)",
        "turf-hover": "rgb(var(--turf-hover) / <alpha-value>)",
        ball: "rgb(var(--ball) / <alpha-value>)",
        snow: "rgb(var(--snow) / <alpha-value>)",
        "snow-dim": "rgb(var(--snow-dim) / <alpha-value>)",
        danger: "#fb7185",
        "danger-solid": "#e11d48",
        "danger-hover": "#be123c",
        "danger-surface": "#2a151f",
        "danger-border": "#7f1d3a",
        "status-pending": "#fbbf24",
        "status-pending-bg": "#2c2207",
        "status-playing": "#818cf8",
        "status-playing-bg": "#171530",
        "status-delivering": "#a78bfa",
        "status-ended-bg": "#1d1530",
        "status-processed": "#34d399",
        "status-processed-bg": "#0c2620",
        "status-cancelled": "#fb7185",
        "status-cancelled-bg": "#2a151f",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md: "0.875rem",
        lg: "1.25rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        "3xl": "2.25rem",
      },
      boxShadow: {
        glow: "0 18px 45px -26px rgb(var(--racket) / 0.42)",
        "glow-sm": "0 10px 28px -20px rgb(var(--racket) / 0.4)",
        card: "0 18px 50px -36px rgb(0 0 0 / 0.45)",
      },
      backgroundImage: {
        "violet-grad": "linear-gradient(135deg, rgb(var(--racket)) 0%, rgb(var(--ball)) 100%)",
        "violet-soft":
          "linear-gradient(160deg, rgb(var(--racket) / 0.12) 0%, rgb(var(--ball) / 0.05) 100%)",
      },
    },
  },
  plugins: [],
};
